### ISSUE TITLE
Project health

### ISSUE THREAD

**Issue by alalamav** [albertolalama/cordova-plugin-tun2socks#14]
- [ ] Add LICENSE
- [ ] Add CONTRIBUTING
  * [ ] Include code style guide
- [ ] Add CHANGELOG
- [ ] Add [.editorconfig](http://editorconfig.org)
- [ ] README improvements
  * [ ] High-level tun2socks
  * [ ] Environment setup
  * [ ] Document release process
- [ ] Add links to the specifications for all relevant protocols (e.g. SOCKS, DNS, etc.) in code comments/docs (as well as any other particularly useful references)

**Comment by jab** [comment]
Migrated to https://buganizer.corp.google.com/issues/37267129
